### ISSUE TITLE
firebase-client-jvm 2.5.0 doesn't work.  

### ISSUE THREAD

**Issue by hex6ng** [firebase/seed-java#1]
Not sure where to file issues for firebase-client-jvm so I thought I'd put it here.
Firebase method calls don't seem to do anything.   AuthResultHandler, CompletionListener, ValueEventListener callbacks don't get executed at all.

**Comment by puf** [comment]
This is probably better suited for StackOverflow. Please post a minimal,
complete code snippet that reproduces the problem
<http://stackoverflow.com/help/mcve> you're having there and I'll have a
look.
